/*!
 * NetPlanning Engine
 * Antonino Parisi <tabman83@gmail.com>
 *
 * File name:	convertTimeZone.js
 * Created:		19/11/2015
 * Description:	Converts NetPlanning timezone display name to UTC time zone
 */

var async = require('async');

module.exports = function convertTimeZone(timeZoneDisplayName) {

    var table = {
        'GMT-12:00': 'Etc/GMT+12',
        'GMT-11:00': 'Etc/GMT+11',
        'Samoa Standard Time': 'Pacific/Midway',
        'Niue Time': 'Pacific/Niue',
        'Samoa Standard Time': 'US/Samoa',
        'Hawaii-Aleutian Daylight Time': 'America/Atka',
        'GMT-10:00': 'Etc/GMT+10',
        'Hawaii Standard Time': 'Pacific/Honolulu',
        'Cook Is. Time': 'Pacific/Rarotonga',
        'Tahiti Time': 'Pacific/Tahiti',
        'Hawaii-Aleutian Daylight Time': 'US/Aleutian',
        'Hawaii Standard Time': 'US/Hawaii',
        'Marquesas Time': 'Pacific/Marquesas',
        'GMT-09:00': 'Etc/GMT+9',
        'Gambier Time': 'Pacific/Gambier',
        'Alaska Standard Time': 'SystemV/YST9',
        'Alaska Daylight Time': 'US/Alaska',
        'Pacific Daylight Time': 'America/Los_Angeles',
        'Metlakatla Standard Time': 'America/Metlakatla',
        'GMT-08:00': 'Etc/GMT+8',
        'Pitcairn Standard Time': 'Pacific/Pitcairn',
        'Pacific Standard Time': 'SystemV/PST8',
        'Mountain Daylight Time': 'Canada/Mountain',
        'GMT-07:00': 'Etc/GMT+7',
        'Mountain Daylight Time': 'Mexico/BajaSur',
        'Mountain Standard Time': 'US/Arizona',
        'Central Standard Time': 'America/El_Salvador',
        'Central Daylight Time': 'US/Central',
        'Colombia Time': 'America/Bogota',
        'Eastern Standard Time': 'America/Cayman',
        'Eastern Daylight Time': 'America/Detroit',
        'Acre Time': 'America/Eirunepe',
        'Easter Is. Summer Time': 'Pacific/Easter',
        'Ecuador Time': 'America/Guayaquil',
        'Cuba Daylight Time': 'America/Havana',
        'GMT-06:00': 'Etc/GMT+6',
        'Galapagos Time': 'Pacific/Galapagos',
        'Peru Time': 'America/Lima',
        'Acre Time': 'America/Porto_Acre',
        'Acre Time': 'America/Rio_Branco',
        'Eastern Daylight Time': 'America/Thunder_Bay',
        'Eastern Daylight Time': 'America/Toronto',
        'Acre Time': 'Brazil/Acre',
        'Eastern Daylight Time': 'Canada/Eastern',
        'Cuba Daylight Time': 'Cuba',
        'Eastern Standard Time': 'EST',
        'Eastern Daylight Time': 'EST5EDT',
        'GMT-05:00': 'Etc/GMT+5',
        'Venezuela Time': 'America/Caracas',
        'Atlantic Standard Time': 'America/Aruba',
        'Paraguay Summer Time': 'America/Asuncion',
        'Amazon Time': 'America/Boa_Vista',
        'Amazon Summer Time': 'America/Campo_Grande',
        'Guyana Time': 'America/Guyana',
        'Atlantic Daylight Time': 'America/Halifax',
        'Bolivia Time': 'America/La_Paz',
        'Amazon Time': 'America/Porto_Velho',
        'Chile Summer Time': 'America/Santiago',
        'Chile Summer Time': 'Antarctica/Palmer',
        'Chile Summer Time': 'Chile/Continental',
        'GMT-04:00': 'Etc/GMT+4',
        'Newfoundland Daylight Time': 'Canada/Newfoundland',
        'Argentine Time': 'AGT',
        'Brasilia Time': 'America/Araguaina',
        'Argentine Time': 'America/Argentina/Buenos_Aires',
        'French Guiana Time': 'America/Cayenne',
        'Western Greenland Summer Time': 'America/Godthab',
        'Pierre & Miquelon Daylight Time': 'America/Miquelon',
        'Uruguay Summer Time': 'America/Montevideo',
        'Suriname Time': 'America/Paramaribo',
        'Brasilia Summer Time': 'America/Sao_Paulo',
        'Rothera Time': 'Antarctica/Rothera',
        'Falkland Is. Time': 'Atlantic/Stanley',
        'Brasilia Summer Time': 'Brazil/East',
        'GMT-03:00': 'Etc/GMT+3',
        'Fernando de Noronha Time': 'America/Noronha',
        'South Georgia Standard Time': 'Atlantic/South_Georgia',
        'Fernando de Noronha Time': 'Brazil/DeNoronha',
        'GMT-02:00': 'Etc/GMT+2',
        'Eastern Greenland Summer Time': 'America/Scoresbysund',
        'Azores Summer Time': 'Atlantic/Azores',
        'Cape Verde Time': 'Atlantic/Cape_Verde',
        'GMT-01:00': 'Etc/GMT+1',
        'Greenwich Mean Time': 'Africa/Abidjan',
        'Ghana Mean Time': 'Africa/Accra',
        'Western European Summer Time': 'Africa/Casablanca',
        'Central European Summer Time': 'Antarctica/Troll',
        'GMT+00:00': 'Etc/GMT',
        'Coordinated Universal Time': 'Etc/UCT',
        'British Summer Time': 'Europe/Belfast',
        'Irish Summer Time': 'Europe/Dublin',
        'Central European Time': 'Africa/Algiers',
        'Western African Time': 'Africa/Brazzaville',
        'Central European Time': 'Africa/Tunis',
        'Western African Summer Time': 'Africa/Windhoek',
        'Central European Summer Time': 'Arctic/Longyearbyen',
        'GMT+01:00': 'Etc/GMT-1',
        'Middle Europe Summer Time': 'MET',
        'Central African Time': 'Africa/Blantyre',
        'Eastern European Summer Time': 'Africa/Cairo',
        'Central African Time': 'Africa/Harare',
        'South Africa Standard Time': 'Africa/Mbabane',
        'Eastern European Time': 'Africa/Tripoli',
        'Eastern European Summer Time': 'Asia/Amman',
        'Israel Daylight Time': 'Asia/Jerusalem',
        'GMT+02:00': 'Etc/GMT-2',
        'Eastern European Time': 'Libya',
        'Eastern African Time': 'Africa/Addis_Ababa',
        'Syowa Time': 'Antarctica/Syowa',
        'Arabia Standard Time': 'Asia/Baghdad',
        'Eastern African Time': 'EAT',
        'GMT+03:00': 'Etc/GMT-3',
        'Further-eastern European Time': 'Europe/Minsk',
        'Eastern African Time': 'Indian/Antananarivo',
        'Iran Daylight Time': 'Asia/Tehran',
        'Azerbaijan Summer Time': 'Asia/Baku',
        'Gulf Standard Time': 'Asia/Dubai',
        'Georgia Time': 'Asia/Tbilisi',
        'Armenia Time': 'Asia/Yerevan',
        'GMT+04:00': 'Etc/GMT-4',
        'Samara Time': 'Europe/Samara',
        'Seychelles Time': 'Indian/Mahe',
        'Mauritius Time': 'Indian/Mauritius',
        'Reunion Time': 'Indian/Reunion',
        'Armenia Time': 'NET',
        'Afghanistan Time': 'Asia/Kabul',
        'Mawson Time': 'Antarctica/Mawson',
        'Aqtau Time': 'Asia/Aqtau',
        'Aqtobe Time': 'Asia/Aqtobe',
        'Turkmenistan Time': 'Asia/Ashkhabad',
        'Tajikistan Time': 'Asia/Dushanbe',
        'Pakistan Time': 'Asia/Karachi',
        'Oral Time': 'Asia/Oral',
        'Uzbekistan Time': 'Asia/Samarkand',
        'GMT+05:00': 'Etc/GMT-5',
        'French Southern & Antarctic Lands Time': 'Indian/Kerguelen',
        'Maldives Time': 'Indian/Maldives',
        'Pakistan Time': 'PLT',
        'India Standard Time': 'Asia/Calcutta',
        'Nepal Time': 'Asia/Kathmandu',
        'Vostok Time': 'Antarctica/Vostok',
        'Alma-Ata Time': 'Asia/Almaty',
        'Kirgizstan Time': 'Asia/Bishkek',
        'Bangladesh Time': 'Asia/Dacca',
        'China Standard Time': 'Asia/Kashgar',
        'Qyzylorda Time': 'Asia/Qyzylorda',
        'Bhutan Time': 'Asia/Thimphu',
        'Bangladesh Time': 'BST',
        'GMT+06:00': 'Etc/GMT-6',
        'Indian Ocean Territory Time': 'Indian/Chagos',
        'Myanmar Time': 'Asia/Rangoon',
        'Cocos Islands Time': 'Indian/Cocos',
        'Davis Time': 'Antarctica/Davis',
        'Indochina Time': 'Asia/Ho_Chi_Minh',
        'Hovd Time': 'Asia/Hovd',
        'West Indonesia Time': 'Asia/Jakarta',
        'Novosibirsk Time': 'Asia/Novokuznetsk',
        'Indochina Time': 'Asia/Phnom_Penh',
        'West Indonesia Time': 'Asia/Pontianak',
        'Indochina Time': 'Asia/Saigon',
        'Indochina Time': 'Asia/Vientiane',
        'GMT+07:00': 'Etc/GMT-7',
        'Christmas Island Time': 'Indian/Christmas',
        'Indochina Time': 'VST',
        'Western Standard Times(Australia)': 'Antarctica/Casey',
        'Brunei Time': 'Asia/Brunei',
        'Choibalsan Time': 'Asia/Choibalsan',
        'China Standard Time': 'Asia/Chongqing',
        'Hong Kong Time': 'Asia/Hong_Kong',
        'Malaysia Time': 'Asia/Kuala_Lumpur',
        'China Standard Time': 'Asia/Macau',
        'Central Indonesia Time': 'Asia/Makassar',
        'Philippines Time': 'Asia/Manila',
        'China Standard Time': 'Asia/Shanghai',
        'Singapore Time': 'Asia/Singapore',
        'China Standard Time': 'Asia/Taipei',
        'Central Indonesia Time': 'Asia/Ujung_Pandang',
        'Ulaanbaatar Time': 'Asia/Ulaanbaatar',
        'Western Standard Times(Australia)': 'Australia/West',
        'China Standard Time': 'CTT',
        'GMT+08:00': 'Etc/GMT-8',
        'Hong Kong Time': 'Hongkong',
        'Singapore Time': 'Singapore',
        'Central Western Standard Times(Australia)': 'Australia/Eucla',
        'Timor-Leste Time': 'Asia/Dili',
        'East Indonesia Time': 'Asia/Jayapura',
        'Korea Standard Time': 'Asia/Pyongyang',
        'Japan Standard Time': 'Asia/Tokyo',
        'GMT+09:00': 'Etc/GMT-9',
        'Palau Time': 'Pacific/Palau',
        'Korea Standard Time': 'ROK',
        'Central Standard Times(Northern Territory)': 'ACT',
        'Central Summer Times(South Australia)': 'Australia/Adelaide',
        'Central Summer Times(South Australia/New South Wales)': 'Australia/Broken_Hill',
        'Central Standard Times(Northern Territory)': 'Australia/Darwin',
        'Central Summer Times(South Australia)': 'Australia/South',
        'Central Summer Times(South Australia/New South Wales)': 'Australia/Yancowinna',
        'Eastern Summer Times(New South Wales)': 'AET',
        'Dumont-d\'Urville Time': 'Antarctica/DumontDUrville',
        'Eastern Summer Times(New South Wales)': 'Australia/ACT',
        'Eastern Standard Times(Queensland)': 'Australia/Brisbane',
        'Eastern Summer Times(New South Wales)': 'Australia/Canberra',
        'Eastern Summer Times(Tasmania)': 'Australia/Hobart',
        'Eastern Standard Times(Queensland)': 'Australia/Lindeman',
        'Eastern Summer Times(Victoria)': 'Australia/Melbourne',
        'Eastern Summer Times(Victoria)': 'Australia/Victoria',
        'GMT+10:00': 'Etc/GMT-10',
        'Chuuk Time': 'Pacific/Chuuk',
        'Chamorro Standard Time': 'Pacific/Guam',
        'Papua New Guinea Time': 'Pacific/Port_Moresby',
        'Chamorro Standard Time': 'Pacific/Saipan',
        'Chuuk Time': 'Pacific/Truk',
        'Chuuk Time': 'Pacific/Yap',
        'Lord Howe Summer Time': 'Australia/LHI',
        'Macquarie Island Time': 'Antarctica/Macquarie',
        'GMT+11:00': 'Etc/GMT-11',
        'Vanuatu Time': 'Pacific/Efate',
        'Solomon Is. Time': 'Pacific/Guadalcanal',
        'Kosrae Time': 'Pacific/Kosrae',
        'New Caledonia Time': 'Pacific/Noumea',
        'Pohnpei Time': 'Pacific/Pohnpei',
        'Solomon Is. Time': 'SST',
        'Norfolk Time': 'Pacific/Norfolk',
        'New Zealand Daylight Time': 'Antarctica/McMurdo',
        'Anadyr Time': 'Asia/Anadyr',
        'Petropavlovsk-Kamchatski Time': 'Asia/Kamchatka',
        'GMT+12:00': 'Etc/GMT-12',
        'Marshall Islands Time': 'Kwajalein',
        'New Zealand Daylight Time': 'Pacific/Auckland',
        'Fiji Summer Time': 'Pacific/Fiji',
        'Tuvalu Time': 'Pacific/Funafuti',
        'Marshall Islands Time': 'Pacific/Majuro',
        'Nauru Time': 'Pacific/Nauru',
        'Gilbert Is. Time': 'Pacific/Tarawa',
        'Wake Time': 'Pacific/Wake',
        'Wallis & Futuna Time': 'Pacific/Wallis',
        'Chatham Daylight Time': 'Pacific/Chatham',
        'GMT+13:00': 'Etc/GMT-13',
        'West Samoa Daylight Time': 'Pacific/Apia',
        'Phoenix Is. Time': 'Pacific/Enderbury',
        'Tokelau Time': 'Pacific/Fakaofo',
        'Tonga Time': 'Pacific/Tongatapu',
        'GMT+14:00': 'Etc/GMT-14',
        'Line Is. Time': 'Pacific/Kiritimati',
        'GMT+11:00': 'Pacific/Bougainville',
        'Yakutsk Time': 'Asia/Yakutsk',
        'Further-eastern European Time': 'Europe/Kaliningrad',
        'Volgograd Time': 'Europe/Volgograd',
        'Magadan Time': 'Asia/Magadan',
        'GMT+11:00': 'Asia/Srednekolymsk',
        'Khandyga Time': 'Asia/Khandyga',
        'Yekaterinburg Time': 'Asia/Yekaterinburg',
        'Vladivostok Time': 'Asia/Vladivostok',
        'Moscow Standard Time': 'Europe/Simferopol',
        'Ust-Nera Time': 'Asia/Ust-Nera',
        'Omsk Time': 'Asia/Omsk',
        'Novosibirsk Time': 'Asia/Novosibirsk',
        'Sakhalin Time': 'Asia/Sakhalin',
        'Krasnoyarsk Time': 'Asia/Krasnoyarsk',
        'GMT+08:00': 'Asia/Chita',
        'Irkutsk Time': 'Asia/Irkutsk',
        'Moscow Standard Time': 'Europe/Moscow',
        'Eastern Standard Time': 'America/Grand_Turk'
    };

    return table[timeZoneDisplayName];
};
